### PR TITLE
Motion peekabo slider fix

### LINKED ISSUE #34: iPhone X - Motion and Peekaboo selectors sit too high up
This is an issue in both portrait and landscape. @alex-taffe I will take this one.

image-1-4

### PR DESCRIPTION
**Pull request by alex-taffe**
Fixes #34

### CODE REVIEW

File: TriggertrapUIKit/HorizontalPicker.m [hunk 1]
```diff
@@ -177,14 +188,17 @@ - (UICollectionViewCell *)collectionView:(UICollectionView *)collectionView cell
         for (UIView *subview in [cell.contentView subviews]) {
             [subview removeFromSuperview];
         }
-        
-        UILabel *textLabel = [[UILabel alloc] initWithFrame:CGRectMake(0, 0, [self width] / 3, [self height])];
-        
+        UILabel *textLabel;
+        if (@available(iOS 11.0, *)) {
+            textLabel = [[UILabel alloc] initWithFrame:CGRectMake(0, 0, [self width] / 3, [self height])];
```
Comment (Ross-Gibson) [inline TriggertrapUIKit/HorizontalPicker.m]: Hey @alex-taffe, Im not sure if this is necessary. Both cases in the if/else look the same to me.

Comment (alex-taffe) [reply TriggertrapUIKit/HorizontalPicker.m]: My bad, was playing around with stuff and forgot to remove that once it became identical

**Review by Ross-Gibson — APPROVED** [review]
