### PR TITLE
Low volume spacing fix

### LINKED ISSUE #26: Low volume notification is covered by iPhone X notch
img_6956
img_6956_iphonexspacegrey_portrait

### PR DESCRIPTION
**Pull request by alex-taffe**
This includes changes from #38 and should not be merged until then

Also, I removed MPGNotification from the actual project and changed it to a cocoa pod. The newer version has support for iPhone X so that was most of our issue, but it’s also just good to get it out of the project. You’ll need to run a `pod update; pod install` before this compiles most likely

Fixes #26

### CODE REVIEW

File: TriggertrapSLR/TTViewController.swift [hunk 1]
```diff
@@ -164,14 +165,15 @@ class TTViewController: SplitLayoutViewController, DispatchableLifecycle, Sequen
...
-                self.notification?.titleColor = UIColor.triggertrap_fillColor()
-                self.notification?.show()
-                self.notification?.duration = 2.0
-            }
+            self.notification?.backgroundColor = UIColor.triggertrap_primaryColor()
+            self.notification?.titleColor = UIColor.triggertrap_fillColor()
+            self.notification?.duration = 2.0
+            self.notification?.show()
+            //this needs to be reinstantiated each time to avoid glitchy behavior (sadly)
+            self.notification = MPGNotification(title: NSLocalizedString("Low Volume", comment: "Low Volume"),
```
Comment (Ross-Gibson) [inline TriggertrapSLR/TTViewController.swift]: @alex-taffe can you explain a bit more the reasoning for this? What exactly is the "glitchy behaviour" and how does this resolve it?

Also, why have we removed the check for `isAnimating`, will that not cause multiple notifications to stack on-top of each other?

**Comment by alex-taffe** [comment]
@Ross-Gibson without the reinstantiation I get this weird bug. I’m not really sure why and I've messed around with the threading for awhile to see if that’s the issue, but I honestly don't know
[YAXP2849.MP4.zip](https://github.com/Triggertrap/triggertrap-ios/files/2036986/YAXP2849.MP4.zip)

As for the is animating, that property does not exist anymore in the library (as of the iPhone X fix). There is a `dismissHandler` property on the notification object, but the library is written in Objective C so of course it’s not playing super nice with swift. I’ll play around with it more to get it set up to avoid stacking.

As for the design, also part of the library change. Lemme look into it more

**Comment by alex-taffe** [comment]
@Ross-Gibson I got everything fixed minus the instantiation problem, which I have no idea how to fix
